/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package worktogether;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Desktop;
import javax.swing.*;
import java.io.*;
import java.net.*;


/**
 *
 * @author Peter
 */
public class WorkTogether extends javax.swing.JFrame {

    /**
     * Creates new form WorkTogether
     */
    
    int signIn = 0;
    
    //Stack overflow
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    
    public WorkTogether() {
        initComponents();
        
        //Stack Overflow
        setSize(screenSize.width, screenSize.height);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        clientPanel = new javax.swing.JPanel();
        clientBackBtn = new javax.swing.JButton();
        clientTitleLbl = new javax.swing.JLabel();
        clientExitBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        clientCommentTxtArea = new javax.swing.JTextArea();
        clientEditBtn = new javax.swing.JButton();
        commentsPanel = new javax.swing.JPanel();
        commentsBackBtn = new javax.swing.JButton();
        commentsExitBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainCommentTxtArea = new javax.swing.JTextArea();
        addCommentsTxtFeild = new javax.swing.JTextField();
        sendBtn = new javax.swing.JButton();
        commentsTitleLbl = new javax.swing.JLabel();
        jobFilePanel = new javax.swing.JPanel();
        file4Btn = new javax.swing.JButton();
        fileTitleLbl = new javax.swing.JLabel();
        file1Btn = new javax.swing.JButton();
        file2Btn = new javax.swing.JButton();
        file3Btn = new javax.swing.JButton();
        editFileBtn = new javax.swing.JButton();
        fileBackBtn = new javax.swing.JButton();
        fileExitBtn = new javax.swing.JButton();
        jobInfoPanel = new javax.swing.JPanel();
        jobNameLbl = new javax.swing.JLabel();
        jobBackBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        extraInfoTxtArea = new javax.swing.JTextArea();
        jobExitBtn = new javax.swing.JButton();
        filesBtn = new javax.swing.JButton();
        clientBtn = new javax.swing.JButton();
        commentsBtn = new javax.swing.JButton();
        jobListPanel = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        job4Bth = new javax.swing.JButton();
        activeJobsLbl = new javax.swing.JLabel();
        job1Btn = new javax.swing.JButton();
        job2Btn = new javax.swing.JButton();
        job3Btn = new javax.swing.JButton();
        jiob6Btn = new javax.swing.JButton();
        job5Btn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        titlePagePanel = new javax.swing.JPanel();
        TitleLbl = new javax.swing.JLabel();
        userNameTxtFeild = new javax.swing.JTextField();
        signInBtn = new javax.swing.JButton();
        passwordLbl = new javax.swing.JLabel();
        UserNameLbl = new javax.swing.JLabel();
        passwordTxtFeild = new javax.swing.JPasswordField();

        jToggleButton1.setText("jToggleButton1");

        jToggleButton2.setText("jToggleButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clientPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clientBackBtn.setText("⬅");
        clientPanel.add(clientBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        clientTitleLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clientTitleLbl.setText("(Job Name)");
        clientPanel.add(clientTitleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        clientExitBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clientExitBtn.setText("X");
        clientPanel.add(clientExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 0, 40, -1));

        clientCommentTxtArea.setColumns(20);
        clientCommentTxtArea.setRows(5);
        jScrollPane3.setViewportView(clientCommentTxtArea);

        clientPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 280, 180));

        clientEditBtn.setText("Edit Information");
        clientPanel.add(clientEditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        commentsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        commentsBackBtn.setText("⬅");
        commentsPanel.add(commentsBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        commentsExitBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        commentsExitBtn.setText("X");
        commentsPanel.add(commentsExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 0, 40, -1));

        mainCommentTxtArea.setColumns(20);
        mainCommentTxtArea.setRows(5);
        jScrollPane1.setViewportView(mainCommentTxtArea);

        commentsPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 280, 180));
        commentsPanel.add(addCommentsTxtFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 200, 30));

        sendBtn.setText("Send");
        commentsPanel.add(sendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 70, 30));

        commentsTitleLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        commentsTitleLbl.setText("(Job Name)");
        commentsPanel.add(commentsTitleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jobFilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        file4Btn.setText("File 4");
        jobFilePanel.add(file4Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 90, -1));

        fileTitleLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fileTitleLbl.setText("(Job Name)");
        jobFilePanel.add(fileTitleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        file1Btn.setText("File 1");
        jobFilePanel.add(file1Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 90, -1));

        file2Btn.setText("File 2");
        jobFilePanel.add(file2Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 90, -1));

        file3Btn.setText("File 3");
        jobFilePanel.add(file3Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 90, -1));

        editFileBtn.setText("Edit Files");
        jobFilePanel.add(editFileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 130, -1));

        fileBackBtn.setText("⬅");
        jobFilePanel.add(fileBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        fileExitBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fileExitBtn.setText("X");
        jobFilePanel.add(fileExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 0, 40, -1));

        jobInfoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jobNameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jobNameLbl.setText("(Job name)");
        jobInfoPanel.add(jobNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jobBackBtn.setText("⬅");
        jobInfoPanel.add(jobBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        extraInfoTxtArea.setColumns(20);
        extraInfoTxtArea.setRows(5);
        jScrollPane2.setViewportView(extraInfoTxtArea);

        jobInfoPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, 100));

        jobExitBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jobExitBtn.setText("X");
        jobInfoPanel.add(jobExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 0, 40, -1));

        filesBtn.setText("Veiw Files");
        jobInfoPanel.add(filesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 150, -1));

        clientBtn.setText("Veiw Client Information");
        jobInfoPanel.add(clientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 150, -1));

        commentsBtn.setText("View Comments");
        jobInfoPanel.add(commentsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 170, -1));

        jobListPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titleLbl.setText("Work Together");
        jobListPanel.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        job4Bth.setText("Job 4");
        jobListPanel.add(job4Bth, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 90, -1));

        activeJobsLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        activeJobsLbl.setText("Active Jobs:");
        jobListPanel.add(activeJobsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        job1Btn.setText("Job 1");
        job1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                job1BtnActionPerformed(evt);
            }
        });
        jobListPanel.add(job1Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, -1));

        job2Btn.setText("Job 2");
        jobListPanel.add(job2Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, -1));

        job3Btn.setText("Job 3");
        jobListPanel.add(job3Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, -1));

        jiob6Btn.setText("Job 6");
        jobListPanel.add(jiob6Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 90, -1));

        job5Btn.setText("Job 5");
        jobListPanel.add(job5Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 90, -1));

        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exitBtn.setText("X");
        jobListPanel.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 40, -1));

        titlePagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TitleLbl.setText("Work Together");
        titlePagePanel.add(TitleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 130, 30));
        titlePagePanel.add(userNameTxtFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 250, -1));

        signInBtn.setText("Sign In");
        signInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInBtnActionPerformed(evt);
            }
        });
        titlePagePanel.add(signInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        passwordLbl.setText("Password");
        titlePagePanel.add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        UserNameLbl.setText("User Name");
        titlePagePanel.add(UserNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));
        titlePagePanel.add(passwordTxtFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jobListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jobInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jobFilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(commentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(clientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jobListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jobInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jobFilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(commentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(clientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInBtnActionPerformed
        signIn();
    }//GEN-LAST:event_signInBtnActionPerformed

    private void job1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_job1BtnActionPerformed
       
        
    }//GEN-LAST:event_job1BtnActionPerformed

    /**
     * This method is responsible for signing in
     */
    public void signIn(){
    
        //Assigning the file readers to variables
        File dataFile = new File("signIn.dat");
        FileReader in;
        BufferedReader readFile;
       
        //Variables
        String username = userNameTxtFeild.getText();
        String password = passwordTxtFeild.getText();
        String passwordPulled;
        String usernamePulled;
        int error = 0;
        int passwordCheck = 0;
        int usernameCheck = 0;
        
        //Running the file reader to see if the user entered a valid account and password
        try{
            
            //Setting variables to readers
            in = new FileReader(dataFile);
            readFile = new BufferedReader(in);
            
            //Setting information gathered from file to varibles
            usernamePulled = readFile.readLine();
            passwordPulled = readFile.readLine();
            
            //Making sure that the user entered a password and username
            if(username.charAt(0) != ' ' && password.charAt(0) != ' '){
                while (passwordCheck < password.length()) {

                    if (password.charAt(passwordCheck) != passwordPulled.charAt(passwordCheck)) {
                        error = 2;
                        throw new Exception("Error");
                    }
                    passwordCheck++;
                }
                while (usernameCheck < username.length()) {

                    if (username.charAt(usernameCheck) != usernamePulled.charAt(usernameCheck)) {
                        error = 1;
                        throw new Exception("Error");
                    }
                    usernameCheck++;
                }
                
                }
            else{

                error = 1;
                throw new Exception("Error");
            }
            
            if(username.length() != usernamePulled.length() || password.length() != passwordPulled.length()){
                error = 1;
                throw new Exception("Error");
            }
            
            
            if (error == 0){
                //Hiding the main sign in screen
                titlePagePanel.hide();

                //Displaying and resizing job list
                jobListPanel.show();

                //Came From Stack Overflow
                titlePagePanel.setSize(screenSize.width, screenSize.height);
                

            }
            readFile.close();
            in.close();
            signIn = 1;
        }
        //Catching
        catch (FileNotFoundException e) {
            System.out.println("File does not exist or could not be found.");
            System.err.println("FileNotFoundException: " + e.getMessage());
        } 
        catch (IOException e) {
            System.out.println("Problem reading file.");
            System.err.println("IOException: " + e.getMessage());
    	}
        
        catch (Exception e){
            if (error == 1){
                System.err.println("You must enter a username that is the same as your account created");
                System.err.println("Exception: " + e);
            }
            else if (error == 2){
                System.err.println("You must enter the same password as the one you created");
                System.err.println("Exception: " + e);
            }
            }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkTogether.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkTogether.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkTogether.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkTogether.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkTogether().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JLabel UserNameLbl;
    private javax.swing.JLabel activeJobsLbl;
    private javax.swing.JTextField addCommentsTxtFeild;
    private javax.swing.JButton clientBackBtn;
    private javax.swing.JButton clientBtn;
    private javax.swing.JTextArea clientCommentTxtArea;
    private javax.swing.JButton clientEditBtn;
    private javax.swing.JButton clientExitBtn;
    private javax.swing.JPanel clientPanel;
    private javax.swing.JLabel clientTitleLbl;
    private javax.swing.JButton commentsBackBtn;
    private javax.swing.JButton commentsBtn;
    private javax.swing.JButton commentsExitBtn;
    private javax.swing.JPanel commentsPanel;
    private javax.swing.JLabel commentsTitleLbl;
    private javax.swing.JButton editFileBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextArea extraInfoTxtArea;
    private javax.swing.JButton file1Btn;
    private javax.swing.JButton file2Btn;
    private javax.swing.JButton file3Btn;
    private javax.swing.JButton file4Btn;
    private javax.swing.JButton fileBackBtn;
    private javax.swing.JButton fileExitBtn;
    private javax.swing.JLabel fileTitleLbl;
    private javax.swing.JButton filesBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JButton jiob6Btn;
    private javax.swing.JButton job1Btn;
    private javax.swing.JButton job2Btn;
    private javax.swing.JButton job3Btn;
    private javax.swing.JButton job4Bth;
    private javax.swing.JButton job5Btn;
    private javax.swing.JButton jobBackBtn;
    private javax.swing.JButton jobExitBtn;
    private javax.swing.JPanel jobFilePanel;
    private javax.swing.JPanel jobInfoPanel;
    private javax.swing.JPanel jobListPanel;
    private javax.swing.JLabel jobNameLbl;
    private javax.swing.JTextArea mainCommentTxtArea;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JPasswordField passwordTxtFeild;
    private javax.swing.JButton sendBtn;
    private javax.swing.JButton signInBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JPanel titlePagePanel;
    private javax.swing.JTextField userNameTxtFeild;
    // End of variables declaration//GEN-END:variables
}
